### ISSUE TITLE
Minimal working example?

### ISSUE THREAD

**Issue by ZweiEuro** [mia-z/capacitor-websocket#4]
Hi!

I am trying to use this library, and after installing I am trying to get anything to happen.
From the source and the docs I'd assume calling `connect` with a socket name that has not been 'build' yet should cause a throw but nothing happens. 
This is the code I am testing it with, there is a websocket server running on the other end in python which works fine when connecting to it from a testing tool (SimpleWebsocket plugin for chrome).

Test WS server:
```python
#!/usr/bin/env python

import asyncio
import websockets
import os

async def echo(websocket, path):
    async for message in websocket:
        print ("Received and echoing message: "+message, flush=True)
        await websocket.send(message)

start_server = websockets.serve(echo, "0.0.0.0", os.environ.get('PORT') or 8080)

print("WebSockets echo server starting", flush=True)
asyncio.get_event_loop().run_until_complete(start_server)

print("WebSockets echo server running", flush=True)
asyncio.get_event_loop().run_forever()
```

Client Code:

```TS
const socketName = 'wsSelection';
const devicePort = "8080"

const optBase: OptionsBase = {
  name: socketName,
};

// bulk subscribe to all events
const events = [
  'message',
  'connected',
  'disconnected',
  'statechange',
  'closeframe',
  'connecterror',
  'error',
  'messageerror',
  'senderror',
  'textnessageerror',
  'textmessage',
];

export async function connect_socket_and_subscribe(ip: string) {
  await CapacitorWebsocket.build({
    name: socketName,
    url: `ws://${ip}:${devicePort}/api/v10/ws`,
  });
  console.log(`ws://${ip}:${devicePort}/api/v10/ws`);

  await events.forEach(async (event) => {
    console.log('sub event', `${socketName}:${event}`);
    await CapacitorWebsocket.addListener(
      `${socketName}:${event}` as any,
      (event) => {
        console.log(`${socketName}:${event} event`, event);
      },
    );
  });

  console.log('connected to socket');
  await CapacitorWebsocket.connect(optBase);

  CapacitorWebsocket.send({
    name: socketName,
    data: 'hello',
  });
}
```

Log output:
```
ws://192.168.0.172:60583/api/v10/ws
socket.ts:33 sub event wsSelection:message
socket.ts:33 sub event wsSelection:connected
socket.ts:33 sub event wsSelection:disconnected
socket.ts:33 sub event wsSelection:statechange
socket.ts:33 sub event wsSelection:closeframe
socket.ts:33 sub event wsSelection:connecterror
socket.ts:33 sub event wsSelection:error
socket.ts:33 sub event wsSelection:messageerror
socket.ts:33 sub event wsSelection:senderror
socket.ts:33 sub event wsSelection:textnessageerror
socket.ts:33 sub event wsSelection:textmessage
socket.ts:42 connected to socket
```

No idea why its not doing anything. In my case I am building the code with webpack but this has worked perfectly well with any other capacitor plugin so I don't think that this is the issue. I get 0 warnings or errors in the console.

Working my way backwards from the implementation I'd expect at least some sort of error or something

**Comment by mia-z** [comment]
I think I see the issue here -- Theres a function called "CapacitorWebsocket.applyListeners". 

You didnt ever call this function which maps the underlying listeners in the respective java/swift implementation (has no effect in the Web version). Thatll also be the reason you didnt get an error; it probably connected fine, and you created the listeners for your app, but didnt call the function i mentioned which wires the listeners up. 

Curious to know what platform youre using too, since I havent tested this a whole lot on capacitor web, only really on android/ios. 

See lines 117, 129 and 130 [here](https://github.com/mia-z/dgg-capacitor-app/blob/main/src/hooks/useChat.ts#L113) where ive used it on my app. (might seem a bit confusing since i have a local function with the name "applyListeners", but that one's separate from the plugin's "applyListeners").

For capacitor web, the CapacitorWebsocket.applyListeners function does nothing, its just specifically needed for java/swift and thus must be used if youre using it for android/ios devices.

**Comment by ZweiEuro** [comment]
Currently i am just referring to the web implementation, which shouldn't need "applyListeners" but doesn't respond regardless.

On Web i can also see on the server that no connection was established.

Rephrasing: "Does this plugin work on web at all ? If yes, what would be a minimal example?"

**Comment by mia-z** [comment]
> "Does this plugin work on web at all ? If yes, what would be a minimal example?"

I've done some _very_ minimal tests with web and it seemed to work fine. The example you gave also _looks_ like it should work. I'm gonna do a few tests tonight and get back to you. 

Can I ask: are you planning on using this on iOS or Android?

**Comment by mia-z** [comment]
Ok the web implementation just had some silly errors that meant it wouldnt work at all.

Made it a bit better now in https://github.com/mia-z/capacitor-websocket/commit/196a2324389591bf7198aec2f3c0e5499ca4b10b

It'll say its properly connected if onopen is called. If an error is throw then youll know about it.
